site_name: 'Systems Thinking for Technologists'
nav:
  - Home: index.md
  - Table of Contents: table-of-contents.md
  - Part 1 Introduction:
    - Forward: intro/forward.md
    - Preface: intro/preface.md
    - Acknowledgements: intro/acknowledgements.md
    - About this book: intro/about-this-book.md
    - About the Author: intro/about-the-authors.md
    - Ch 1 Introduction: intro/ch-01-intro.md
    - Ch 2 Graphs: intro/ch-02-graph.md
    - Ch 3 Systems Thinking: intro/ch-03-systems.md
    - Ch 4 Graph Systems Thinking: intro/ch-04-systems-graph.md
  - Part 2 Archetypes:
    - Introduction: archetypes/ch-05-totc.md
    - Tragedy of the Commons: archetypes/commons.md
    - The AI Flywheel: archetypes/ai-flywheel.md
    - Concept Standards: archetypes/concept-standards.md
    - Search and Reuse: archetypes/search-and-reuse.md
  # - Render Tests:
  #  - render-tests/mermaid-test.md
  #  - render-tests/state-diagram.md
  #  - render-tests/influence-diagram.md
  #  - Chapter X: concepts/graph.md
  #  - Chapter X+1: concepts/graph.md
  #- Pt 3 Case Studies:
  # - Part 3 Case Studies:
  #   - Chapter 9: case-studies/healthcare.md
  - Increasing Maturity:
    - Introduction: cmm-strategies/index.md
    - Microstrategies: cmm-strategies/microstrategies.md
    - Silo Busting Microstrategies: cmm-strategies/silo-busting-microstrategies.md
  - Archetypes: archetypes.md
  - Glossary: glossary.md
  - What They Are Saying: what-they-are-saying.md
  - Colophon: colophon.md
  - References: references.md
  - Contact: contact.md

site_description: 'Book on Graphs and Systems Thinking'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/graph-systems-thinking'

edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
plugins:
    - search
# I was trying to do the causal loop diagrams with Markup
# It kind of works but slows down the build
#    - mermaid2
# markdown_extensions:
#   - codehilite:
#       linenums: true
